#!/usr/bin/env python
# -*- coding: utf-8 -*-

#---------------------------------------------------------------------
# This file is part of the Tango SPEC device server
#
# Copyright (c) 2014, European Synchrotron Radiation Facility.
# Distributed under the GNU Lesser General Public License.
# See LICENSE.txt for more info.
#---------------------------------------------------------------------

"""A TANGO device server for SPEC based on SpecClient."""

def main():
    import logging
    logging.basicConfig(level=logging.DEBUG,
                        format="%(threadName)10s %(asctime)s "
                        "%(levelname)5s %(name)s: %(message)s")

    try:
        from TangoSpec import run
    except ImportError:
        import os
        import sys
        path = os.path.realpath(os.path.join(os.path.dirname(__file__),
                                             os.path.pardir))
        sys.path.append(path)
        from TangoSpec import run

    run()

if __name__ == "__main__": 
    main()
